# Generated by Django 2.0.2 on 2018-02-11 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('caption', models.CharField(max_length=128)),
                ('template', models.CharField(max_length=64)),
                ('infoText', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('ACT', 'Active'), ('SUS', 'Suspended'), ('DEL', 'Deleted')], max_length=5)),
                ('infoText', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartyContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=512)),
                ('infoText', models.CharField(blank=True, max_length=255, null=True)),
                ('contactType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ContactType')),
            ],
        ),
        migrations.CreateModel(
            name='PartyHasRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infoText', models.CharField(blank=True, max_length=255, null=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Party')),
            ],
        ),
        migrations.CreateModel(
            name='PartyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('caption', models.CharField(max_length=60)),
                ('infoText', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=64)),
                ('destPartyHasRole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destPartyHasRole', to='core.PartyHasRole')),
            ],
        ),
        migrations.CreateModel(
            name='RelationshipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=64)),
                ('srcDef', models.CharField(max_length=45)),
                ('dstDef', models.CharField(max_length=45)),
                ('infoText', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=128)),
                ('roleFlag', models.CharField(max_length=8)),
                ('infoText', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='relationship',
            name='relationshipType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.RelationshipType'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='srcPartyHasRole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='srcPartyHasRole', to='core.PartyHasRole'),
        ),
        migrations.AddField(
            model_name='partyhasrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Role'),
        ),
        migrations.AddField(
            model_name='party',
            name='partyContact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PartyContact'),
        ),
        migrations.AddField(
            model_name='party',
            name='partyType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PartyType'),
        ),
    ]
