# Generated by Django 2.0.2 on 2018-02-11 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNumber', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=128)),
                ('issueAuth', models.CharField(max_length=255)),
                ('passportCol', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='PassportType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=45)),
                ('infoText', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(max_length=100)),
                ('endDate', models.DateField(max_length=100)),
                ('firstName', models.CharField(max_length=45)),
                ('secondName', models.CharField(max_length=45)),
                ('patronymic', models.CharField(max_length=45)),
                ('birthDate', models.DateField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('taxCode', models.CharField(max_length=18)),
                ('infoText', models.CharField(blank=True, max_length=255, null=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Party')),
            ],
        ),
        migrations.AddField(
            model_name='passport',
            name='passportType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PassportType'),
        ),
        migrations.AddField(
            model_name='passport',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Person'),
        ),
    ]
