# Generated by Django 2.0.2 on 2018-02-11 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180211_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='patronymic',
            new_name='patronymicName',
        ),
    ]
