# Generated by Django 2.0.2 on 2018-02-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_organization_organizationcategory_organizationhasorganizationcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
            ],
        ),
    ]
