# Generated by Django 2.0.2 on 2018-02-15 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_dbaccess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='partyContact',
        ),
        migrations.AddField(
            model_name='partycontact',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Party'),
        ),
    ]
