# Generated by Django 2.0.2 on 2018-02-18 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180215_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=128)),
                ('infoText', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonHasPersonCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infoText', models.CharField(blank=True, max_length=255, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Person')),
                ('personCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PersonCategory')),
            ],
        ),
        migrations.RemoveField(
            model_name='passport',
            name='passportCol',
        ),
        migrations.AddField(
            model_name='passport',
            name='infoText',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
